apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orderingestion-api-ingress
  namespace: orderingestion-api-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx

  # TLS for your real domain (works once DNS is ready)
  tls:
    - hosts:
        - api.orderingestion.com
      secretName: orderingestion-api-tls-secret

  rules:
    # Rule for real domain
    - host: api.orderingestion.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orderingestion-api
                port:
                  number: 80

    # Hostless rule for testing via IP
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orderingestion-api
                port:
                  number: 80
