apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orderingestion-ingress
  namespace: orderingestion-api-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.orderingestion.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orderingestion-api
                port:
                  number: 80
  tls:
    - hosts:
        - api.orderingestion.com
      secretName: orderingestion-api-tls-secret
