# -----------------------------
# 1. Create Namespace
# -----------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: orderingestion-api-prod
---
# -----------------------------
# 1. Deployment
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingestion-api
  namespace: orderingestion-api-prod
  labels:
    app: orderingestion-api
spec:
  replicas: 2
  #zero-downtime deployment using RollingUpdate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: orderingestion-api
  template:
    metadata:
      labels:
        app: orderingestion-api
    spec:
      containers:
        - name: orderingestion-api
          image: orderingestionacr.azurecr.io/orderingestion-api:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
             - name: ASPNETCORE_URLS
               value: "http://+:80"
          envFrom:
            - secretRef:
                name: db-connection
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "orderingestion-kv-provider"
      imagePullSecrets:
        - name: acr-auth

          
        