# -----------------------------
# 3. Service (LoadBalancer)
# -----------------------------

apiVersion: v1
kind: Service
metadata:
  name: orderingestion-api
  namespace: orderingestion-api-prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: orderingestion-api
