# -----------------------------
# 3. Service (LoadBalancer)
# -----------------------------

apiVersion: v1
kind: Service
metadata:
  name: orderingestion-api
  namespace: orderingestion-api-prod
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000       # public port
      targetPort: 8080 # container port
  selector:
    app: orderingestion-api
