# -----------------------------
# 3. Service (ClusterIP)
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: orderingestion-api
  namespace: orderingestion-api-prod
spec:
  type: ClusterIP   # must be ClusterIP for NGINX ingress routing
  selector:
    app: orderingestion-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80