name: CI/CD - Terraform → Lint → Test → Docker Build & Push → AKS Deployment

on:
  push:
    branches:
      - master  
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  IMAGE_NAME: orderingestion-api
  NAMESPACE: orderingestion-api-prod
   
jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      #Terraform setup before any Terraform command.  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
          
      # Authenticate to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve tfplan
        
  build-and-deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore and build
      - name: Restore dependencies
        run: dotnet restore ./OrderIngestionAPI/OrderIngestionAPI.csproj

      - name: Build
        run: dotnet build ./OrderIngestionAPI/OrderIngestionAPI.csproj --configuration Release --no-restore

      # Run Automated Tests
      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --collect "XPlat Code Coverage"

      ## Lint C# Code
      #- name: C# Linting (dotnet format)
      #  run: dotnet format --verify-no-changes
      #  continue-on-error: true

      # Lint Dockerfile
      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: OrderIngestionAPI/Dockerfile

      ## Lint Kubernetes YAML
      #- name: Lint Kubernetes YAML
      #  uses: ibiqlik/action-yamllint@v3.1.1
      #  with:
      #    config_file: .yamllint.yml

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry (ACR)
      - name: Login to ACR
        run: |
          az acr login --name $ACR_LOGIN_SERVER
          #echo ${{ secrets.ACR_PASSWORD }} | docker login $ACR_LOGIN_SERVER -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Build and push OrderIngestion API
      - name: Build & Push API Docker Image
        run: |
          docker build -t $ACR_LOGIN_SERVER/orderingestion-api:latest -f OrderIngestionAPI/Dockerfile .
          docker push $ACR_LOGIN_SERVER/orderingestion-api:latest
          
      # Connect to AKS
      - name: Connect to AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          
      
      # Deploy apps to AKS
      # Update deployment image
      - name: Update deployment image(Deploy API to AKS)
        run: |
          kubectl set image deployment/${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}=$ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:latest -n ${{ env.NAMESPACE }}

      # Check rollout status
      - name: Check rollout status
        run: |
          kubectl rollout status deployment/${{ env.IMAGE_NAME }} -n ${{ env.NAMESPACE }}
          
      # Ensure namespace exists
      - name: Ensure namespace exists
        run: |
          kubectl get namespace ${{ env.NAMESPACE }} || kubectl create namespace ${{ env.NAMESPACE }}

      # Apply deployment manifest
      - name: Apply deployment manifest
        run: |
          kubectl apply -f k8s/self-signed-deployment.yaml -n ${{ env.NAMESPACE }}        
          kubectl rollout restart deployment/${{ env.IMAGE_NAME }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.IMAGE_NAME }} -n ${{ env.NAMESPACE }}
          